apiVersion: v1
kind: Service
metadata:
  name: vdc-service
spec:
  selector:
    app: vdc
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
    nodePort: 30009
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdc
spec:
  selector:
    matchLabels:
      app: vdc
  replicas: 1
  template:
    metadata:
      labels:
        app: vdc
    spec:
      containers:
      - name: vdc
        image: vdc:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
